config/routes.rb
Rails.application.routes.draw do
  mount_activeadmin_settings()
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  get 'about' => 'pages#about'
  get 'delivery' => 'pages#delivery'
  resource :contacts, only: :create
  resources :products, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :reviews, only: :index
  resources :contacts, only: :index
  resources :orders, except: :index do
    get 'success', on: :member
  end
  root to: 'pages#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attached_file :image,
                    styles: {
                        resized: "625x290",
                        thumb: "500x290",
                        large: "1020x600"
                    }
  validates_attachment :image, content_type: { :content_type => ["image/jpg", "image/jpeg", "image/png"] }
  validates_presence_of :title, :body, :image

  default_scope { order(updated_at: :desc) }

  paginates_per 11

  def to_s
    title
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_many :options
  validates_presence_of :name

  def to_s
    name
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  include ActiveadminSettings::Helpers
  attribute :subject
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true

  def headers
    {
        :subject => "Сообщение с сайта mnp-stroy.ru",
        :to => settings_value('Email'),
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders

  validates :name, :phone, presence: true

  def to_s
    name
  end
end

app/models/option.rb
class Option < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_and_belongs_to_many :orders
  belongs_to :category

  validates_presence_of :name, :price, :category

  scope :ordered, -> {order(id: :asc)}

  def to_s
    name
  end

  def to_label
    "#{id}. #{name} (#{decorate.price})".html_safe
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :customer
  has_and_belongs_to_many :options
  accepts_nested_attributes_for :customer

  validates :customer, presence: true, allow_blank: false

  def to_s
    "Заказ №#{id}"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_images
  belongs_to :category
  has_and_belongs_to_many :options
  accepts_nested_attributes_for :product_images, allow_destroy: true

  validates_presence_of :name, :price
  paginates_per 16

  default_scope { order(index: :desc) }

  scope :featured, -> { where(featured: true) }
  scope :in_price_range, -> (min, max) {
    min.present? && max.present? ? where(price: min..max) : all
  }
  scope :in_category, -> (id) {
    id.present? ? where(category_id: id) : all
  }

  def to_s
    name
  end

  def cover
    product_images.first_or_create.image
  end

  def self.price_range
    {
        min: BigDecimal(self.pluck(:price).min).floor(-3).to_i,
        max: BigDecimal(self.pluck(:price).max).ceil(-3).to_i
    }
  end

  def self.text_search(query)
    if query.present?
      where("name @@ :q or description @@ :q", q: query)
    else
      all
    end
  end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image,
                    styles: {
                        thumb: "249x197>",
                        medium: "419x285>"
                    },
                    convert_options: {
                        thumb: "-resize 249x197^ -gravity center -extent 249x197",
                        medium: "-resize 419x285^ -gravity center -extent 419x285"
                    },
                    default_url: ':style/product-default.jpg'

  validates_attachment :image, content_type: { :content_type => ["image/jpg", "image/jpeg", "image/png"] }

  default_scope{ order(created_at: :asc)}
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_attached_file :photo,
                    styles: {
                        thumb: "80x80>"
                    },
                    convert_options: {
                        thumb: "-resize 80x80^ -gravity center -extent 80x80"
                    }
  validates_attachment :photo, content_type: { :content_type => ["image/jpg", "image/jpeg", "image/png"] }
  validates_presence_of :name, :photo, :body

  default_scope { order(updated_at: :desc) }

  paginates_per 10

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :global_keywords

  def global_keywords
    Product.all.map(&:name)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.page(params[:page])
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      gflash :success => "Спасибо, сообщение отправлено успешно. Мы свяжемся с вами в ближайшее время"
      redirect_to contacts_path
    else
      render action: 'index'
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_order, only: [:show, :update, :success]

  def create
    order_params[:option_ids] = order_params[:option_ids].split(',')
    @order = Order.new(order_params)
    if @order.save(validate: false)
      redirect_to order_path(@order)
    else
      render "show"
    end
  end

  def update
    status_changed = @order.status != order_params[:status]
    if @order.update(order_params)
      OrderMailer.new_order(@order).deliver if status_changed
      render 'success'
    else
      render 'show'
    end
  end

  def show
    @order.customer ||= Customer.new
  end

  private

  def order_params
    params.require(:order).permit!
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @products = Product.includes(:product_images).featured
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_categories

  def index
    @products = Product.text_search(params[:query]).in_category(params[:category]).in_price_range(params[:min], params[:max]).page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def set_categories
    @categories = Category.includes(:products)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def size(i)
    pattern = %w(1 3 2 2 4 4 4 3 1 2 2)
    "size#{pattern[i]}"
  end

end

app/views/articles/_articles_list.slim
.articles-list
  - articles.each_with_index do |article, i|
    figure class= size(i)
      .cover style="background-image: url('#{article.image.url(:resized)}')"
      figcaption
        time #{time_ago_in_words article.updated_at} назад
        h2 = article
      = link_to '', article_path(article), class: 'read-more'

app/views/articles/index.js.erb
$('.articles-list').append("<%= j render 'articles/articles_list', articles: @articles %>");

<% if @articles.last_page? %>
  $('.show-more').remove();
<% end %>

app/views/articles/index.slim
- title 'Новости'

section.block.articles@@paginated data-path=articles_path
  h1 Новости
  = render 'articles/articles_list', articles: @articles
  - unless @articles.last_page?
    .show-more: a.btn.btn-outline.btn-green@load_more href="#" Показать еще

app/views/articles/show.slim
- title @article

section.article
  header
    .cover style="background-image: url('#{@article.image.url(:large)}')"
    .title
      time #{time_ago_in_words @article.updated_at} назад
      h2 = @article

  section.block
    article
      = @article.body.html_safe
      .share-links
        div#ya_share1

app/views/contacts/index.slim
- title 'Контакты'

- content_for :scripts do
  = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true&language=ru"
  = javascript_include_tag 'gmaps'

section.contacts
  div@@map
    #map-frame
  .content
    = simple_form_for @contact || Contact.new do |f|
      .row
        = f.input :name
        = f.input :email
      = f.input :subject
      = f.input :message, as: :text, input_html: {rows: 8}, placeholder: (placeholder if defined? placeholder)
      = f.button :submit
    ul.contact-info
      li
        span.label> Телефон:
        = phone_link_to settings_value('Телефон')
      li
        span.label> Email:
        = mail_to settings_value('Email')
      li
        span.label> Адрес:
        = settings_value('Адрес')
      li
        span.label> Мы работаем:
        = settings_value('Часы работы')

app/views/layouts/_header.slim
header
  = link_to root_path, class: 'logo'
    = svg_image_tag 'logo.svg', size: '250x55'
  = form_tag products_path, method: :get, class: 'search-form'
    = search_field_tag :query, params[:query], placeholder: "Найти что-нибудь..."
    = button_tag(type: 'submit', name: nil) do
      i.ion-ios-search-strong
  = phone_link_to settings_value('Телефон'), class: 'phone-link'
  = link_to 'Ваша заявка', contacts_path, class: 'btn btn-small'
nav
  = active_link_to 'продукция', products_path
  = active_link_to 'новости', articles_path
  = active_link_to 'о компании', about_path
  = active_link_to 'доставка', delivery_path
  = active_link_to 'отзывы', reviews_path
  = active_link_to 'контакты', contacts_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=1100" name="viewport" /
    = stylesheet_link_tag    "application", media: 'all'
    = yield :scripts
    = javascript_include_tag "application"
    = favicon_link_tag 'favicon.png'
    = csrf_meta_tags
    = metamagic site: settings_value("Название сайта"),
                description: settings_value("Описание сайта"),
                keywords: global_keywords + [settings_value("Ключевые слова")],
                title: [:title, :site], separator: " – "

  body
    .wrapper
      main
        = render 'layouts/header'
        = yield
    footer
      .content
        p &copy; Компания «Монпарнас РСК», 2014
        p
          |Дизайн и разработка
          = link_to "http://4isten.co/",  target:"_blank" do
            = svg_image_tag '4istenco.svg', size: '80x14'

    = render 'layouts/metrika'
    = gflash
    script type="text/javascript" src="http://consultsystems.ru/script/5400/" charset="utf-8"

app/views/orders/show.slim
section.block.order
  h1 = @order
  table.order-details
    tr
      td: h4 = @order.product
      td = @order.product.decorate.price

    - @order.options.each do |option|
      tr
        td = option
        td = option.decorate.price

    tr
      td Колличество
      td = @order.quantity
    tr
      td.price colspan=2 Итого: #{@order.decorate.price}


  = simple_form_for @order do |f|
    = f.hidden_field :status, value: 'Оформлен'
    = f.simple_fields_for :customer do |c|
      = c.input :name
      = c.input :phone
      = c.input :email
    = f.input :comment, as: :text, input_html: {rows: 5}
    = f.button :submit, 'Оформить заказ'

app/views/orders/success.slim
section.block.success
  p
    |Ваш заказ
    strong<> №#{@order.id}
    |успешно оформлен.
    br
    |Наш оператор свяжется с вами в ближайшее время. Спасибо.

app/views/pages/about.slim
- title 'О компании'

section.page.about
  header
    .text
      h1 О компании
      = simple_format settings_value("Кратко о компании")
  section.block
    article
      = settings_value("Текст о компании")

app/views/pages/delivery.slim
- title 'Доставка'

section.page.delivery
  header
    .text
      h1 Доставка
      = simple_format settings_value("Кратко о доставке")
  section.block
    article
      = settings_value("Текст о доставке")

app/views/pages/index.slim
section.index
  header
    .centered
      h2 наша продукция
      h1 Экологична
      = simple_format settings_value("Текст на главной")
      = link_to 'Узнать подробнее', about_path, class: 'btn btn-outline btn-white'

  section.products-slider
    div.slider@@products_slider
      - @products.each do |product|
        figure.product-preview
          = image_tag product.cover.url(:thumb), size: '248x196'
          figcaption
            h5 = truncate product.name, length: 25, separator: ' '
            .price = product.decorate.price
          = link_to '', product_path(product), class: 'show-more'

  section.block.articles
    h1 Новости
    = render 'articles/articles_list', articles: Article.limit(4)
    .show-more
      = link_to 'Показать все новости', articles_path, class: 'btn'

  section.block.benefits
    h1 наши преимущества
    .benefits-list
      figure
        = svg_image_tag 'benefit1.svg', size: '125x125'
        figcaption Лучшие решения для бизнеса и дома
      figure
        = svg_image_tag 'benefit2.svg', size: '125x125'
        figcaption Тщательный контроль на всех этапах
      figure
        = svg_image_tag 'benefit3.svg', size: '125x125'
        figcaption Бесплатный выезд менеджера

  section.block.dark.reviews
    h1 Отзывы покупателей
    .reviews-list
      = render Review.limit(4)
    .show-more
      = link_to 'Показать все все отзывы', reviews_path, class: 'btn btn-outline btn-green'

app/views/products/_product.slim
figure.product-preview
  = link_to product_path(product) do
    = image_tag product.cover.url(:thumb)
  figcaption
    h5 = truncate product.name, length: 50, separator: ' '
    p = truncate product.description, length: 80, separator: ' '
    .price = product.decorate.price
    = link_to 'Приобрести', product_path(product), class: 'btn btn-small'

app/views/products/index.js.erb
$('.products-list').append("<%=j render @products %>");

<% if @products.last_page? %>
  $('.show-more').remove();
<% end %>

app/views/products/index.slim
- title 'Каталог продукции'

section.products@@paginated data-path=products_path
  header
    .categories
      h1 Каталог продукции
      h1 Обзор
      .categories-list
        = active_link_to products_path, active: params[:category].nil? do
          .counter = Product.count
          |Все товары
        - @categories.each do |category|
          = active_link_to params.merge(category: category.id), active: params[:category].to_i == category.id do
            .counter = category.products.count
            = category
    .price-range@@price_range
      .range-slider
        span.label Фильтр по цене
        div@range data={min: Product.price_range[:min], max: Product.price_range[:max], from: params[:min], to: params[:max]}
        button@submit class='btn btn-small' Применить

  section.products-list
    = render @products

  - unless @products.last_page?
    .show-more: a.btn.btn-outline.btn-green@load_more href="#" Показать еще

app/views/products/show.slim
- title @product

section.block.dark.product
  .product-image-slider@@product_image_slider
    ul.slider@slider
      -@product.product_images.each do |product_image|
        li =image_tag product_image.image.url(:medium), size: "419x285"
    -unless @product.product_images.count == 1
      .pager@pager
        -@product.product_images.each_with_index do |product_image, i|
          a data-slide-index="#{i}" href=""
            =image_tag product_image.image.url(:thumb), size: "137x91"
  .description@@product_options
    h2 = @product
    hr
    - if @product.description.present?
      = simple_format @product.description
      hr
    - if @product.properties.present?
      table.properties
        -@product.properties.split("\n").each do |option|
          tr
            -option.split(":").each do |part|
              td =part
      hr
    - if @product.options.present?
      h3 Дополнительные услуги:
      table.options
        - @product.options.each do |option|
          tr
            td: label for="option_#{option.id}"= option
            td = option.decorate.price
            td: input@option type="checkbox" value=option.id id="option_#{option.id}" data-price=option.price
      hr

    .summary
      .quantity
        label> for='quantity' Количество:
        input#quantity@quantity type='number' value=1
      .price
        label> Итоговая цена:
        span@total_price = @product.price
        small< руб.
    hr

    = simple_form_for Order.new do |f|
      = f.hidden_field :product_id, value: @product.id
      = f.hidden_field :option_ids, value: "", data: {role: 'options'}
      = f.hidden_field :quantity, value: 1, data: {role: 'quantity'}
      = f.hidden_field :price, value: @product.price, data: {role: 'price_input'}
      = f.button :submit, 'Оформить заказ'

app/views/reviews/_review.slim
article
  = image_tag review.photo.url(:thumb), size: '80x80', class: 'avatar'
  .content
    = simple_format review.body
    h4 = review.name
    p.company-info
      = review.position
      - if review.company_url.present?
        - if review.position.present?
          span<>&#8212;
        = ext_link_to review.company_name || review.company_url, review.company_url
      - elsif review.company_name.present?
        - if review.position.present?
          span<>&#8212;
        = review.company_name

app/views/reviews/index.js.erb
$('.reviews-list').append("<%= j render @reviews %>");

<% if @reviews.last_page? %>
  $('.show-more').remove();
<% end %>

app/views/reviews/index.slim
- title 'Отзывы покупателей'

section.block.dark.reviews@@paginated data-path=reviews_path
  h1 Отзывы покупателей
  .reviews-list
    = render @reviews
  - unless @reviews.last_page?
    .show-more: a.btn.btn-outline.btn-green@load_more href="#" Показать еще